# Generated by Django 4.2.21 on 2025-05-10 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('appointments', '0002_availabilityoverride'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyerprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_client', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_lawyer', to='users.lawyerprofile'),
        ),
        migrations.AlterField(
            model_name='availabilityoverride',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_overrides', to='users.lawyerprofile'),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='users.lawyerprofile'),
        ),
        migrations.DeleteModel(
            name='ClientProfile',
        ),
        migrations.DeleteModel(
            name='LawyerProfile',
        ),
    ]
