# Generated by Django 4.2.21 on 2025-05-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_remove_lawyerprofile_user_alter_appointment_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(blank=True, help_text='Latest known payment status from Stripe', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe PaymentIntent ID', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=15),
        ),
    ]
