# Generated by Django 4.2.21 on 2025-05-10 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('client', 'Client'), ('lawyer', 'Lawyer'), ('admin', 'Admin')], default='client', max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_initial_profile_complete', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LawyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_admission_details', models.TextField(blank=True, help_text="JSON or structured text, e.g., {'state': 'NY', 'bar_number': '12345'}", null=True)),
                ('areas_of_practice', models.TextField(blank=True, help_text='Comma-separated or JSON list of practice areas', null=True)),
                ('office_location_address', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_picture_url', models.URLField(blank=True, max_length=500, null=True)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('education', models.TextField(blank=True, help_text='e.g., Law School, Graduation Year', null=True)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('languages_spoken', models.CharField(blank=True, help_text='Comma-separated list', max_length=255, null=True)),
                ('website_url', models.URLField(blank=True, max_length=255, null=True)),
                ('is_lawyer_specific_profile_complete', models.BooleanField(default=False)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_details', to='users.userprofile')),
            ],
        ),
    ]
